# -*- coding: utf-8 -*-
"""BeautifulSoup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/skanda07/14a8a9207fceb1b91ad9da749b5e7696/beautifulsoup.ipynb
"""

import requests
from bs4 import BeautifulSoup
url="https://codewithharry.com"

#step1: get the html
r=requests.get(url)
htmlcontent=r.content

#Step2:Parse the html
soup=BeautifulSoup(htmlcontent, 'html.parser')
print(soup)
print(soup.prettify)

#step 3: Html Tree traversal
#common used to types of objects:
title=soup.title
print(title)#1. tag
print(type(soup))#2.BeautifulSoup
print(type(title.string))#3.NavigableString
#4.comment

#Get all the paragraphs from the page
para=soup.find_all('p')
#print(para)

#GET all the anchor tags:
anchors=soup.find_all('a')
#get all the links in the page
for link in anchors:
  if(link.get('href')!='#'):
    link="https://codewithharry.com" +link.get('href')
    print(link)

#Get the first  paragraph and class  in the html page
print(soup.find('p')['class'])

#finding all the class elements with class name lead
print(soup.find_all('p',class_="lead"))

#get the text from the tags/soup
txt=soup.find('p').get_text()
print(txt)

#obtaining id tags
nav=soup.find(id='navbarSupportedContent')
for i in nav.contents:
  print(i)

for i in nav.stripped_strings:
  print(i)